### ISSUE TITLE
Only install command line tools when they are not already installed

### ISSUE THREAD

**Issue by mwilliammyers** [mwilliammyers/ansible-xcode#1]
Ref. [tasks/main.yml:6](https://github.com/mkwmms/ansible-xcode/blob/8c7abccbd443bacda7bd72e76c2223778b20886d/tasks/main.yml#L6)

``` yml
  ignore_errors: yes # TODO: Only install command line tools when they are not already installed
  when: ansible_distribution == 'MacOSX'
  tags:
    - bootstrap
    - install

…
```
